infix using "C:\Users\User\Documents\GitHub\labour-force-survey\PretestLFS\household.dct"

label variable cluster  "Cluster"
label variable ghintid  "Interviewer ID"
label variable ghhhno   "Household number"
label variable gharea   "Type of area"
label variable ghvfdt   "Interview date"
label variable ghhrpl   "Household replacement status"
label variable ghhhsize "Number of household members"
label variable ghneligible "Number of eligible household members"
label variable ghintname "Interviewer Name"
label variable dem_str  "Adult member availability"
label variable hc01     "Religion of household head"
label variable hc02     "Language of household head"
label variable hc03     "Ethnic group of household head"
label variable hc10     "Tenure"
label variable hc11     "Main material of roof"
label variable hc12     "Main material of wall"
label variable hc13     "Main material of floor"
label variable hc14     "Number of rooms"
label variable hc15     "Number of sleeping rooms"
label variable hc16     "Household have: Radio"
label variable hc17     "Household: Bed"
label variable hc18     "Household have: Sofa"
label variable hc19     "Household have: Chair"
label variable hc20     "Household have: A water storage tank"
label variable hc21     "Household have: Watch"
label variable hc22     "Household have electricity"
label variable hc23     "Household have: Television"
label variable hc24     "Household have: Refrigerator"
label variable hc25     "Household have: A water pump"
label variable hc26     "Household have: A sewing machine"
label variable hc27     "Household have: A DVD player"
label variable hc28     "Any member of household own: Wristwatch"
label variable hc29     "Any member of household own: Bicycle"
label variable hc30     "Any member of household own: Motorcycle or scooter"
label variable hc31     "Any member of household own: Animal-drawn cart"
label variable hc32     "Any member of household own: Car, truck or van"
label variable hc33     "Any member of household own: Boat with motor"
label variable hc34     "Any member of household: Fishing net"
label variable hc35     "Any member of household own: A canoe"
label variable hc36     "Any member have a computer"
label variable hc37     "Any member have a mobile telephone"
label variable hc38     "Internet access at home"
label variable hc39     "Any household member own land that can be used for agriculture"
label variable hc40     "Unit of Measure  of agricultural land members of household owns"
label variable hc41     "Actual Size of agricultural land member of household owns"
label variable hc42     "Household own any animals"
label variable hc43     "Milk cows or bulls"
label variable hc44     "Other cattle"
label variable hc45     "Horses, donkeys or mules"
label variable hc46     "Goats"
label variable hc47     "Sheep"
label variable hc48     "Chickens"
label variable hc49     "Pigs"
label variable hc50     "Any other Livestock"
label variable hc51     "Any household member own bank account"
label variable lh1      "All sources of household income in last 12 months"
label variable lh2      "Sources of support - other"
label variable lh3      "Main source of household income in last 12 months"
label variable lh4      "Main source of support - other"
label variable lh5      "Thinking of current season"
label variable lh6      "Involved in making decisions"
label variable lh7      "Engaged in family farm work"
label variable lh8      "Engaged in tending work animals"
label variable lh9      "Engaged in family fishing"
label variable lh10     "Intentions of hh produce"
label variable lh11     "Sold or kept"
label variable ws1      "Main source of drinking water"
label variable ws2      "Main source of water used for other purposes (if bottled water used for drinking"
label variable ws3      "Type of toilet facility"
label variable ws4      "Location of the toilet faciltity"
label variable ws5      "Toilet facility shared"
label variable ghunid   "Unique Identifier"
label variable region   "Region"
label variable district "District"
label variable hh_interviewer_code "Interviewer Code"
label variable hh_supervisor_code "Supervisor Code"
label variable hh_start_interview_time "Start Interview Time"
label variable hh_end_interview_time "End Interview Time"
label variable hh_program_publish_date "Program Publish Date"
label variable hh_introduction "Interview Introduction"
label variable hh_conclusion "Interview Conclusion"
label variable hh_gps_reading "GPS Reading"
label variable hh_latitude "GPS Latitude"
label variable hh_longitude "GPS Longitude"
label variable hh_altitude "GPS Altitude"
label variable hh_gps_accuracy "GPS Accuracy"
label variable hh_gps_sat "GPS Satellites"
label variable hh_gps_readtime "GPS Readtime"
label variable p00_population_introduction "P00 Population Section"
label variable d00_dwelling_introduction "D00. Dwelling Characteristics Section"
label variable lh_livelihood_introduction "LH. Sources of Livelihood Section"
label variable e00_emigration_introduction "E00. Emigration Section"
label variable e01_emigration "E01. Emigration in the Last 10 Years"
label variable e07      "Received Cash Remittances"
label variable e08      "Value of Cash Remittances"
label variable e09      "Received Goods as Remittances"
label variable e10      "Value of Goods as Remittances"
label variable hh_resp_ln "Respondent ID"
label variable hmppno   "Unique person number"
label variable p_keep_row "Population Section: Keep Row?"
label variable ppno     "Person number"
label variable dem_name "Name"
label variable dem_01   "Sex"
label variable dem_02   "Relationship to head/reference person"
label variable date_of_birth "Date of birth"
label variable dem_03   "Day of birth"
label variable dem_05   "Year of birth"
label variable dem_04   "Month of birth"
label variable dem_06   "Age"
label variable dem_07   "Marital status"
label variable dem_08   "Literacy"
label variable dem_09   "Ever attended school"
label variable dem_10   "Highest level of education"
label variable dem_11   "Highest class completed"
label variable dem_12   "Highest qualification"
label variable dem_13   "Field of education"
label variable dem_13a  "Field of Education Broad"
label variable dem_13b  "Field of Education Narrow"
label variable dem_13c  "Field of Education Detail"
label variable dem_14   "Country of Birth"
label variable dem_15   "Born in another country"
label variable dem_16   "Year of Arrival"
label variable dem_17   "Number of Years Spent in MW"
label variable dem_18   "Reason of arrival"
label variable dem_19   "Citizen of Malawi"
label variable dem_20   "Other Country Citizenship"
label variable dem_21a  "Dificulty in seeing"
label variable dem_21   "Difficulty seeing severity"
label variable dem_22a  "Difficulty in Hearing"
label variable dem_22   "Difficulty hearing aid"
label variable dem_23   "Difficulty walking"
label variable dem_24   "Difficulty speaking"
label variable dem_25   "Difficulty intellectually"
label variable dem_26   "Self Care"
label variable dem_27   "Albinism"
label variable p_more_rows "Population Section: Roster Confirmation"

#delimit ;
label define GHAREA  
     1 "Urban"
     2 "Peri-urban"
     3 "Rural"
;
label define GHHRPL  
     1 "YES"
     2 "NO"
;
label define DEM_STR 
     1 "YES"
     2 "NO"
;
label define HC01    
     1 "Roman Catholic"
     2 "CCAP"
     3 "SDA/Baptist/Apostolic"
     4 "Muslim"
     5 "Anglican"
     6 "Baptist"
     7 "Jehovas Witness"
     8 "Bible Believer"
     9 "Zambezi Evangelical"
    10 "New Apostolic"
    11 "Church of Christ"
    12 "Pentecostal"
    13 "Hinduism"
    14 "Traditional/Ethnic Religion"
    15 "Other christian denomination"
    16 "Other religion"
    17 "No Religion"
;
label define HC02    
     1 "CHICHEWA"
     2 "CHITUMBUKA"
     3 "CHIYAO"
     4 "CHILOMWE"
     5 "CHITONGA"
     6 "CHISENA"
     7 "CHINKHONDE"
     8 "CHINGONI"
     9 "CHIMANG'ANJA"
    10 "CHINYANJA"
    11 "CHILAMBYA"
    12 "CHISENGA"
    13 "CHINDALI"
    14 "NYAKUSYA"
    96 "OTHER LANGUAGE"
    99 "NO RESPONSE"
;
label define HC03    
     1 "CHEWA"
     2 "TUMBUKA"
     3 "YAO"
     4 "LOMWE"
     5 "TONGA"
     6 "SENA"
     7 "NKHONDE"
     8 "NGONI"
     9 "MANG'ANJA"
    10 "KHOKHOLA"
    11 "NDALI"
    12 "NYANJA"
    13 "LAMBYA"
    96 "OTHER (SPECIFY)"
    99 "NO RESPONSE"
;
label define HC10    
     1 "Owner/Family Occupied"
     2 "Rented"
     3 "Institutional"
     4 "Given for free"
     5 "Other"
;
label define HC11    
     1 "Grass thatch"
     2 "Iron sheets"
     3 "Iron with Tiles"
     4 "Asbestos"
     5 "Cement"
     6 "Other"
;
label define HC12    
     1 "Burnt bricks"
     2 "Unburnt bricks"
     3 "Concrete"
     4 "Cement blocks"
     5 "Mud/Wattle/Dung"
     6 "Reeds/Straw"
     7 "Wood/Planks"
     8 "Other"
;
label define HC13    
     1 "Earth/Sand"
     2 "Dung"
     3 "Wood planks"
     4 "Palm/Bamboo"
     5 "Broken bricks"
     6 "Parquet or polished wood"
     7 "Vinyl or asphalt strips"
     8 "Ceramic tiles"
     9 "Cement"
    10 "Bricks"
    11 "Other"
;
label define HC16    
     1 "YES"
     2 "NO"
;
label define HC17    
     1 "YES"
     2 "NO"
;
label define HC18    
     1 "YES"
     2 "NO"
;
label define HC19    
     1 "YES"
     2 "NO"
;
label define HC20    
     1 "YES"
     2 "NO"
;
label define HC21    
     1 "YES"
     2 "NO"
;
label define HC22    
     1 "YES, INTERCONNECTED GRID"
     2 "YES, OFF-GRID (GENERATOR/ISOLATED SYSTEM)"
     3 "NO"
;
label define HC23    
     1 "YES"
     2 "NO"
;
label define HC24    
     1 "YES"
     2 "NO"
;
label define HC25    
     1 "YES"
     2 "NO"
;
label define HC26    
     1 "YES"
     2 "NO"
;
label define HC27    
     1 "YES"
     2 "NO"
;
label define HC28    
     1 "YES"
     2 "NO"
;
label define HC29    
     1 "YES"
     2 "NO"
;
label define HC30    
     1 "YES"
     2 "NO"
;
label define HC31    
     1 "YES"
     2 "NO"
;
label define HC32    
     1 "YES"
     2 "NO"
;
label define HC33    
     1 "YES"
     2 "NO"
;
label define HC34    
     1 "YES"
     2 "NO"
;
label define HC35    
     1 "YES"
     2 "NO"
;
label define HC36    
     1 "YES"
     2 "NO"
;
label define HC37    
     1 "YES"
     2 "NO"
;
label define HC38    
     1 "YES"
     2 "NO"
;
label define HC39    
     1 "YES"
     2 "NO"
;
label define HC40    
     1 "ACRES"
     2 "HECTARES"
     3 "FOOTBALL PITCHES / GROUND"
    98 "DON`T KNOW"
;
label define HC42    
     1 "YES"
     2 "NO"
;
label define HC43    
  9995 "95+"
;
label define HC44    
  9995 "95+"
;
label define HC45    
  9995 "95+"
;
label define HC46    
  9995 "95+"
;
label define HC47    
  9995 "95+"
;
label define HC48    
  9995 "95+"
;
label define HC49    
  9995 "95+"
;
label define HC50    
  9995 "95+"
;
label define HC51    
     1 "YES"
     2 "NO"
;
label define LH5     
     1 "Yes"
     2 "No"
;
label define LH6     
     1 "Yes"
     2 "No"
;
label define LH7     
     1 "Yes"
     2 "No"
;
label define LH8     
     1 "Yes"
     2 "No"
;
label define LH9     
     1 "Yes"
     2 "No"
;
label define LH10    
     1 "Only for sale"
     2 "Mainly for sale"
     3 "Mainly for family use"
     4 "Only for family use"
     5 "CANNOT SAY (DO NOT READ)"
;
label define LH11    
     1 "Only sold"
     2 "Mainly sold"
     3 "Mainly kept for family use"
     4 "Only kept for family use"
;
label define WS1     
    11 "PIPED WATER: PIPED INTO DWELLING"
    12 "PIPED WATER: PIPED TO YARD / PLOT"
    13 "PIPED WATER: PIPED TO NEIGHBOUR"
    14 "PIPED WATER: PUBLIC TAP / STANDPIPE"
    21 "TUBE WELL / BOREHOLE"
    31 "DUG WELL: PROTECTED WELL"
    32 "DUG WELL: UNPROTECTED WELL"
    41 "SPRING: PROTECTED SPRING"
    42 "SPRING: UNPROTECTED SPRING"
    51 "RAINWATER"
    61 "TANKER-TRUCK"
    71 "CART WITH SMALL TANK"
    72 "WATER KIOSK"
    81 "SURFACE WATER (RIVER, DAM, LAKE, POND, STREAM, CANAL, IRRIGATION CHANNEL)"
    91 "PACKAGED WATER: BOTTLED WATER"
    92 "PACKAGED WATER: SACHET WATER"
    96 "OTHER"
;
label define WS2     
    11 "PIPED WATER: PIPED INTO DWELLING"
    12 "PIPED WATER: PIPED TO YARD / PLOT"
    13 "PIPED WATER: PIPED TO NEIGHBOUR"
    14 "PIPED WATER: PUBLIC TAP / STANDPIPE"
    21 "TUBE WELL / BOREHOLE"
    31 "DUG WELL: PROTECTED WELL"
    32 "DUG WELL: UNPROTECTED WELL"
    41 "SPRING: PROTECTED SPRING"
    42 "SPRING: UNPROTECTED SPRING"
    51 "RAINWATER"
    61 "TANKER-TRUCK"
    71 "CART WITH SMALL TANK"
    72 "WATER KIOSK"
    81 "SURFACE WATER (RIVER, DAM, LAKE, POND, STREAM, CANAL, IRRIGATION CHANNEL)"
    96 "OTHER"
;
label define WS3     
    11 "FLUSH / POUR FLUSH: FLUSH TO PIPED SEWER SYSTEM"
    12 "FLUSH / POUR FLUSH: FLUSH TO SEPTIC TANK"
    13 "FLUSH / POUR FLUSH: FLUSH TO PIT LATRINE"
    14 "FLUSH / POUR FLUSH: FLUSH TO OPEN DRAIN"
    18 "FLUSH / POUR FLUSH: FLUSH TO DK WHERE"
    21 "PIT LATRINE: VENTILATED IMPROVED PIT LATRINE"
    22 "PIT LATRINE: PIT LATRINE WITH SLAB"
    23 "PIT LATRINE: PIT LATRINE WITHOUT SLAB / OPEN PIT"
    31 "COMPOSTING TOILET"
    41 "BUCKET"
    51 "HANGING TOILET / HANGING LATRINE"
    95 "NO FACILITY / BUSH / FIELD"
    96 "OTHER"
;
label define WS4     
     1 "IN OWN DWELLING"
     2 "IN OWN YARD / PLOT"
     3 "ELSEWHERE"
;
label define WS5     
     1 "YES"
     2 "NO"
;
label define HH_INTRODUCTION
     1 "Begin interview"
;
label define HH_CONCLUSION
     1 "Conclude interview"
     2 "Review population section"
     3 "Review dwelling characteristics section"
     4 "Review emigration section"
;
label define HH_GPS_READING
     1 "Yes"
     2 "No"
;
label define P00_POPULATION_INTRODUCTION
     1 "Continue"
;
label define D00_DWELLING_INTRODUCTION
     1 "Continue"
;
label define LH_LIVELIHOOD_INTRODUCTION
     1 "Continue"
;
label define E00_EMIGRATION_INTRODUCTION
     1 "Continue"
;
label define E01_EMIGRATION
     1 "Yes"
     2 "No"
;
label define E07     
     1 "Yes"
     2 "No"
     3 "Don't know"
;
label define E08     
999999998 "Don't Know"
999999999 "Refused"
;
label define E09     
     1 "Yes"
     2 "No"
     3 "Don't know"
;
label define E10     
999999998 "Don't Know"
999999999 "Refused"
;
label define P_KEEP_ROW
     1 "Yes, keep population row"
     2 "No, delete population row"
;
label define DEM_01  
     1 "MALE"
     2 "FEMALE"
;
label define DEM_02  
     2 "Wife or husband"
     3 "Son or daughter"
     4 "Son-in-law or daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother or sister"
     9 "Niece or nephew"
    10 "Co-wife"
    11 "Other relative"
    12 "Grandparent"
    13 "Step-son or Step-daughter"
    14 "Domestic worker"
    15 "Not related"
;
label define DEM_03  
     1 "1"
     2 "2"
     3 "3"
     4 "4"
     5 "5"
     6 "6"
     7 "7"
     8 "8"
     9 "9"
    10 "10"
    11 "11"
    12 "12"
    13 "13"
    14 "14"
    15 "15"
    16 "16"
    17 "17"
    18 "18"
    19 "19"
    20 "20"
    21 "21"
    22 "22"
    23 "23"
    24 "24"
    25 "25"
    26 "26"
    27 "27"
    28 "28"
    29 "29"
    30 "30"
    31 "31"
;
label define DEM_05  
  9999 "Missing"
;
label define DEM_04  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    99 "Don't know"
;
label define DEM_07  
     1 "NEVER MARRIED"
     2 "MARRIED"
     3 "COHABITING"
     4 "SEPARATED"
     5 "DIVORCED"
     6 "WIDOWED"
;
label define DEM_08  
     1 "Yes"
     2 "No"
;
label define DEM_09  
     1 "Never attended"
     2 "Has ever attended"
     3 "Currently attending"
;
label define DEM_10  
     0 "PRE-SCHOOL"
     1 "PRIMARY"
     2 "SECONDARY"
     3 "UNIVERSITY"
     4 "OTHER TERTIARY"
;
label define DEM_11  
     0 "None"
     1 "Standard 1"
     2 "Standard 2"
     3 "Standard 3"
     4 "Standard 4"
     5 "Standard 5"
     6 "Standard 6"
     7 "Standard 7"
     8 "Standard 8"
     9 "Form 1"
    10 "Form 2"
    11 "Form 3"
    12 "Form 4"
    13 "Form 5"
    14 "Form 6"
    15 "Diploma Year 1"
    16 "Diploma Year 2"
    17 "Diploma Year 3"
    18 "Degree -Year 1"
    19 "Degree -Year 2"
    20 "Degree -Year 3"
    21 "Degree -Year 4"
    22 "Degree -Year 5"
    23 "Masters-Year 1"
    24 "Masters-Year 2"
    25 "PhD-Year 1"
    26 "PhD-Year 2"
    27 "PhD-Year 3"
    28 "PhD-Year 4"
    29 "PhD-Year 5"
    30 "Tertiary-Year 1"
    31 "Tertiary-Year 2"
    32 "Tertiary-Year 3"
    33 "Tertiary-Year 4"
;
label define DEM_12  
     0 "None"
     1 "Primary School Leaving Certificate"
;
label define DEM_13A 
     0 "Generic programmes and qualifications"
     1 "Education"
     2 "Arts and humanities"
     3 "Social sciences, journalism and information"
     4 "Business, administration and law"
     5 "Natural sciences, Mathematics and Statistics"
     6 "Information and Communication Technologies (ICTs)"
     7 "Engineering, manufacturing and construction"
     8 "Agriculture, forestry, fisheries and veterinary"
     9 "Health and welfare"
    10 "Other Area of Study"
;
label define DEM_14  
     1 "Yes"
     2 "No"
;
label define DEM_15  
   894 "Zambia"
   716 "Zimbabwe"
   508 "Mozambique"
   108 "Burundi"
   710 "South Africa"
   646 "Rwanda"
    72 "Botswana"
   706 "Somalia"
   178 "Congo (Brazzaville)"
   180 "Congo, (Kinshasa)"
   356 "India"
   156 "China"
   231 "Ethiopia"
     4 "Afghanistan"
   248 "Aland Islands"
     8 "Albania"
    12 "Algeria"
    16 "American Samoa"
    20 "Andorra"
    24 "Angola"
   660 "Anguilla"
    10 "Antarctica"
    28 "Antigua and Barbuda"
    32 "Argentina"
    51 "Armenia"
   533 "Aruba"
    36 "Australia"
    40 "Austria"
    31 "Azerbaijan"
    44 "Bahamas"
    48 "Bahrain"
    50 "Bangladesh"
    52 "Barbados"
   112 "Belarus"
    56 "Belgium"
    84 "Belize"
   204 "Benin"
    60 "Bermuda"
    64 "Bhutan"
    68 "Bolivia"
    70 "Bosnia and Herzegovina"
    74 "Bouvet Island"
    76 "Brazil"
    92 "British Virgin Islands"
    86 "British Indian Ocean Territory"
    96 "Brunei Darussalam"
   100 "Bulgaria"
   854 "Burkina Faso"
   116 "Cambodia"
   120 "Cameroon"
   124 "Canada"
   132 "Cape Verde"
   136 "Cayman Islands"
   140 "Central African Republic"
   148 "Chad"
   152 "Chile"
   344 "Hong Kong, SAR China"
   446 "Macao, SAR China"
   162 "Christmas Island"
   166 "Cocos (Keeling) Islands"
   170 "Colombia"
   174 "Comoros"
   184 "Cook Islands"
   188 "Costa Rica"
   384 "Côte d'Ivoire"
   191 "Croatia"
   192 "Cuba"
   196 "Cyprus"
   203 "Czech Republic"
   208 "Denmark"
   262 "Djibouti"
   212 "Dominica"
   214 "Dominican Republic"
   218 "Ecuador"
   818 "Egypt"
   222 "El Salvador"
   226 "Equatorial Guinea"
   232 "Eritrea"
   233 "Estonia"
   238 "Falkland Islands (Malvinas)"
   234 "Faroe Islands"
   242 "Fiji"
   246 "Finland"
   250 "France"
   254 "French Guiana"
   258 "French Polynesia"
   260 "French Southern Territories"
   266 "Gabon"
   270 "Gambia"
   268 "Georgia"
   276 "Germany"
   288 "Ghana"
   292 "Gibraltar"
   300 "Greece"
   304 "Greenland"
   308 "Grenada"
   312 "Guadeloupe"
   316 "Guam"
   320 "Guatemala"
   831 "Guernsey"
   324 "Guinea"
   624 "Guinea-Bissau"
   328 "Guyana"
   332 "Haiti"
   334 "Heard and Mcdonald Islands"
   336 "Holy See (Vatican City State)"
   340 "Honduras"
   348 "Hungary"
   352 "Iceland"
   360 "Indonesia"
   364 "Iran, Islamic Republic of"
   368 "Iraq"
   372 "Ireland"
   833 "Isle of Man"
   376 "Israel"
   380 "Italy"
   388 "Jamaica"
   392 "Japan"
   832 "Jersey"
   400 "Jordan"
   398 "Kazakhstan"
   404 "Kenya"
   296 "Kiribati"
   408 "Korea (North)"
   410 "Korea (South)"
   414 "Kuwait"
   417 "Kyrgyzstan"
   418 "Lao PDR"
   428 "Latvia"
   422 "Lebanon"
   426 "Lesotho"
   430 "Liberia"
   434 "Libya"
   438 "Liechtenstein"
   440 "Lithuania"
   442 "Luxembourg"
   807 "Macedonia, Republic of"
   450 "Madagascar"
   458 "Malaysia"
   462 "Maldives"
   466 "Mali"
   470 "Malta"
   584 "Marshall Islands"
   474 "Martinique"
   478 "Mauritania"
   480 "Mauritius"
   175 "Mayotte"
   484 "Mexico"
   583 "Micronesia, Federated States of"
   498 "Moldova"
   492 "Monaco"
   496 "Mongolia"
   499 "Montenegro"
   500 "Montserrat"
   504 "Morocco"
   104 "Myanmar"
   516 "Namibia"
   520 "Nauru"
   524 "Nepal"
   528 "Netherlands"
   530 "Netherlands Antilles"
   540 "New Caledonia"
   554 "New Zealand"
   558 "Nicaragua"
   562 "Niger"
   566 "Nigeria"
   570 "Niue"
   574 "Norfolk Island"
   580 "Northern Mariana Islands"
   578 "Norway"
   512 "Oman"
   586 "Pakistan"
   585 "Palau"
   275 "Palestinian Territory"
   591 "Panama"
   598 "Papua New Guinea"
   600 "Paraguay"
   604 "Peru"
   608 "Philippines"
   612 "Pitcairn"
   616 "Poland"
   620 "Portugal"
   630 "Puerto Rico"
   634 "Qatar"
   638 "Réunion"
   642 "Romania"
   643 "Russian Federation"
   652 "Saint-Barthélemy"
   654 "Saint Helena"
   659 "Saint Kitts and Nevis"
   662 "Saint Lucia"
   663 "Saint-Martin (French part)"
   666 "Saint Pierre and Miquelon"
   670 "Saint Vincent and Grenadines"
   882 "Samoa"
   674 "San Marino"
   678 "Sao Tome and Principe"
   682 "Saudi Arabia"
   686 "Senegal"
   688 "Serbia"
   690 "Seychelles"
   694 "Sierra Leone"
   702 "Singapore"
   703 "Slovakia"
   705 "Slovenia"
    90 "Solomon Islands"
   239 "South Georgia and the South Sandwich Islands"
   728 "South Sudan"
   724 "Spain"
   144 "Sri Lanka"
   736 "Sudan"
   740 "Suriname"
   744 "Svalbard and Jan Mayen Islands"
   748 "Swaziland"
   752 "Sweden"
   756 "Switzerland"
   760 "Syrian Arab Republic (Syria)"
   158 "Taiwan, Republic of China"
   762 "Tajikistan"
   834 "Tanzania, United Republic of"
   764 "Thailand"
   626 "Timor-Leste"
   768 "Togo"
   772 "Tokelau"
   776 "Tonga"
   780 "Trinidad and Tobago"
   788 "Tunisia"
   792 "Turkey"
   795 "Turkmenistan"
   796 "Turks and Caicos Islands"
   798 "Tuvalu"
   800 "Uganda"
   804 "Ukraine"
   784 "United Arab Emirates"
   826 "United Kingdom"
   840 "United States of America"
   581 "US Minor Outlying Islands"
   858 "Uruguay"
   860 "Uzbekistan"
   548 "Vanuatu"
   862 "Venezuela (Bolivarian Republic)"
   704 "Viet Nam"
   850 "Virgin Islands, US"
   876 "Wallis and Futuna Islands"
   732 "Western Sahara"
   887 "Yemen"
    94 "Zambia"
    16 "Zimbabwe"
     8 "Mozambique"
     8 "Burundi"
    10 "South Africa"
    46 "Rwanda"
    72 "Botswana"
     6 "Somalia"
    78 "Congo (Brazzaville)"
    80 "Congo, (Kinshasa)"
    56 "India"
    56 "China"
    31 "Ethiopia"
     4 "Afghanistan"
    48 "Aland Islands"
     8 "Albania"
    12 "Algeria"
    16 "American Samoa"
    20 "Andorra"
    24 "Angola"
    60 "Anguilla"
    10 "Antarctica"
    28 "Antigua and Barbuda"
    32 "Argentina"
    51 "Armenia"
    33 "Aruba"
    36 "Australia"
    40 "Austria"
    31 "Azerbaijan"
    44 "Bahamas"
    48 "Bahrain"
    50 "Bangladesh"
    52 "Barbados"
    12 "Belarus"
    56 "Belgium"
    84 "Belize"
     4 "Benin"
    60 "Bermuda"
    64 "Bhutan"
    68 "Bolivia"
    70 "Bosnia and Herzegovina"
    74 "Bouvet Island"
    76 "Brazil"
    92 "British Virgin Islands"
    86 "British Indian Ocean Territory"
    96 "Brunei Darussalam"
     0 "Bulgaria"
    54 "Burkina Faso"
    16 "Cambodia"
    20 "Cameroon"
    24 "Canada"
    32 "Cape Verde"
    36 "Cayman Islands"
    40 "Central African Republic"
    48 "Chad"
    52 "Chile"
    44 "Hong Kong, SAR China"
    46 "Macao, SAR China"
    62 "Christmas Island"
    66 "Cocos (Keeling) Islands"
    70 "Colombia"
    74 "Comoros"
    84 "Cook Islands"
    88 "Costa Rica"
    84 "Côte d'Ivoire"
    91 "Croatia"
    92 "Cuba"
    96 "Cyprus"
     3 "Czech Republic"
     8 "Denmark"
    62 "Djibouti"
    12 "Dominica"
    14 "Dominican Republic"
    18 "Ecuador"
    18 "Egypt"
    22 "El Salvador"
    26 "Equatorial Guinea"
    32 "Eritrea"
    33 "Estonia"
    38 "Falkland Islands (Malvinas)"
    34 "Faroe Islands"
    42 "Fiji"
    46 "Finland"
    50 "France"
    54 "French Guiana"
    58 "French Polynesia"
    60 "French Southern Territories"
    66 "Gabon"
    70 "Gambia"
    68 "Georgia"
    76 "Germany"
    88 "Ghana"
    92 "Gibraltar"
     0 "Greece"
     4 "Greenland"
     8 "Grenada"
    12 "Guadeloupe"
    16 "Guam"
    20 "Guatemala"
    31 "Guernsey"
    24 "Guinea"
    24 "Guinea-Bissau"
    28 "Guyana"
    32 "Haiti"
    34 "Heard and Mcdonald Islands"
    36 "Holy See (Vatican City State)"
    40 "Honduras"
    48 "Hungary"
    52 "Iceland"
    60 "Indonesia"
    64 "Iran, Islamic Republic of"
    68 "Iraq"
    72 "Ireland"
    33 "Isle of Man"
    76 "Israel"
    80 "Italy"
    88 "Jamaica"
    92 "Japan"
    32 "Jersey"
     0 "Jordan"
    98 "Kazakhstan"
     4 "Kenya"
    96 "Kiribati"
     8 "Korea (North)"
    10 "Korea (South)"
    14 "Kuwait"
    17 "Kyrgyzstan"
    18 "Lao PDR"
    28 "Latvia"
    22 "Lebanon"
    26 "Lesotho"
    30 "Liberia"
    34 "Libya"
    38 "Liechtenstein"
    40 "Lithuania"
    42 "Luxembourg"
     7 "Macedonia, Republic of"
    50 "Madagascar"
    58 "Malaysia"
    62 "Maldives"
    66 "Mali"
    70 "Malta"
    84 "Marshall Islands"
    74 "Martinique"
    78 "Mauritania"
    80 "Mauritius"
    75 "Mayotte"
    84 "Mexico"
    83 "Micronesia, Federated States of"
    98 "Moldova"
    92 "Monaco"
    96 "Mongolia"
    99 "Montenegro"
     0 "Montserrat"
     4 "Morocco"
     4 "Myanmar"
    16 "Namibia"
    20 "Nauru"
    24 "Nepal"
    28 "Netherlands"
    30 "Netherlands Antilles"
    40 "New Caledonia"
    54 "New Zealand"
    58 "Nicaragua"
    62 "Niger"
    66 "Nigeria"
    70 "Niue"
    74 "Norfolk Island"
    80 "Northern Mariana Islands"
    78 "Norway"
    12 "Oman"
    86 "Pakistan"
    85 "Palau"
    75 "Palestinian Territory"
    91 "Panama"
    98 "Papua New Guinea"
     0 "Paraguay"
     4 "Peru"
     8 "Philippines"
    12 "Pitcairn"
    16 "Poland"
    20 "Portugal"
    30 "Puerto Rico"
    34 "Qatar"
    38 "Réunion"
    42 "Romania"
    43 "Russian Federation"
    52 "Saint-Barthélemy"
    54 "Saint Helena"
    59 "Saint Kitts and Nevis"
    62 "Saint Lucia"
    63 "Saint-Martin (French part)"
    66 "Saint Pierre and Miquelon"
    70 "Saint Vincent and Grenadines"
    82 "Samoa"
    74 "San Marino"
    78 "Sao Tome and Principe"
    82 "Saudi Arabia"
    86 "Senegal"
    88 "Serbia"
    90 "Seychelles"
    94 "Sierra Leone"
     2 "Singapore"
     3 "Slovakia"
     5 "Slovenia"
    90 "Solomon Islands"
    39 "South Georgia and the South Sandwich Islands"
    28 "South Sudan"
    24 "Spain"
    44 "Sri Lanka"
    36 "Sudan"
    40 "Suriname"
    44 "Svalbard and Jan Mayen Islands"
    48 "Swaziland"
    52 "Sweden"
    56 "Switzerland"
    60 "Syrian Arab Republic (Syria)"
    58 "Taiwan, Republic of China"
    62 "Tajikistan"
    34 "Tanzania, United Republic of"
    64 "Thailand"
    26 "Timor-Leste"
    68 "Togo"
    72 "Tokelau"
    76 "Tonga"
    80 "Trinidad and Tobago"
    88 "Tunisia"
    92 "Turkey"
    95 "Turkmenistan"
    96 "Turks and Caicos Islands"
    98 "Tuvalu"
     0 "Uganda"
     4 "Ukraine"
    84 "United Arab Emirates"
    26 "United Kingdom"
    40 "United States of America"
    81 "US Minor Outlying Islands"
    58 "Uruguay"
    60 "Uzbekistan"
    48 "Vanuatu"
    62 "Venezuela (Bolivarian Republic)"
     4 "Viet Nam"
    50 "Virgin Islands, US"
    76 "Wallis and Futuna Islands"
    32 "Western Sahara"
    87 "Yemen"
;
label define DEM_16  
  9999 "Missing"
;
label define DEM_17  
     1 "LESS THAN 12 MONTHS"
     2 "1 YEAR TO LESS THAN 5 YRS"
     3 "5 YEARS TO LESS THAN 10 YEARS"
     4 "10 YEARS OR MORE"
;
label define DEM_18  
     1 "TO TAKE UP A JOB"
     2 "JOB TRANSFER"
     3 "TO LOOK FOR WORK, CLIENTS"
     4 "TO STUDY"
     5 "MARRIAGE"
     6 "FAMILY MOVED/JOINING FAMILY"
     7 "MEDICAL TREATMENT, HEALTH"
     8 "CONFLICT, INSECURITY, NATURAL DISASTER"
     9 "LIFESTYLE, COST-OF-LIVING"
    10 "OTHER"
;
label define DEM_20  
   894 "Zambia"
   716 "Zimbabwe"
   508 "Mozambique"
   108 "Burundi"
   710 "South Africa"
   646 "Rwanda"
    72 "Botswana"
   706 "Somalia"
   178 "Congo (Brazzaville)"
   180 "Congo, (Kinshasa)"
   356 "India"
   156 "China"
   231 "Ethiopia"
     4 "Afghanistan"
   248 "Aland Islands"
     8 "Albania"
    12 "Algeria"
    16 "American Samoa"
    20 "Andorra"
    24 "Angola"
   660 "Anguilla"
    10 "Antarctica"
    28 "Antigua and Barbuda"
    32 "Argentina"
    51 "Armenia"
   533 "Aruba"
    36 "Australia"
    40 "Austria"
    31 "Azerbaijan"
    44 "Bahamas"
    48 "Bahrain"
    50 "Bangladesh"
    52 "Barbados"
   112 "Belarus"
    56 "Belgium"
    84 "Belize"
   204 "Benin"
    60 "Bermuda"
    64 "Bhutan"
    68 "Bolivia"
    70 "Bosnia and Herzegovina"
    74 "Bouvet Island"
    76 "Brazil"
    92 "British Virgin Islands"
    86 "British Indian Ocean Territory"
    96 "Brunei Darussalam"
   100 "Bulgaria"
   854 "Burkina Faso"
   116 "Cambodia"
   120 "Cameroon"
   124 "Canada"
   132 "Cape Verde"
   136 "Cayman Islands"
   140 "Central African Republic"
   148 "Chad"
   152 "Chile"
   344 "Hong Kong, SAR China"
   446 "Macao, SAR China"
   162 "Christmas Island"
   166 "Cocos (Keeling) Islands"
   170 "Colombia"
   174 "Comoros"
   184 "Cook Islands"
   188 "Costa Rica"
   384 "Côte d'Ivoire"
   191 "Croatia"
   192 "Cuba"
   196 "Cyprus"
   203 "Czech Republic"
   208 "Denmark"
   262 "Djibouti"
   212 "Dominica"
   214 "Dominican Republic"
   218 "Ecuador"
   818 "Egypt"
   222 "El Salvador"
   226 "Equatorial Guinea"
   232 "Eritrea"
   233 "Estonia"
   238 "Falkland Islands (Malvinas)"
   234 "Faroe Islands"
   242 "Fiji"
   246 "Finland"
   250 "France"
   254 "French Guiana"
   258 "French Polynesia"
   260 "French Southern Territories"
   266 "Gabon"
   270 "Gambia"
   268 "Georgia"
   276 "Germany"
   288 "Ghana"
   292 "Gibraltar"
   300 "Greece"
   304 "Greenland"
   308 "Grenada"
   312 "Guadeloupe"
   316 "Guam"
   320 "Guatemala"
   831 "Guernsey"
   324 "Guinea"
   624 "Guinea-Bissau"
   328 "Guyana"
   332 "Haiti"
   334 "Heard and Mcdonald Islands"
   336 "Holy See (Vatican City State)"
   340 "Honduras"
   348 "Hungary"
   352 "Iceland"
   360 "Indonesia"
   364 "Iran, Islamic Republic of"
   368 "Iraq"
   372 "Ireland"
   833 "Isle of Man"
   376 "Israel"
   380 "Italy"
   388 "Jamaica"
   392 "Japan"
   832 "Jersey"
   400 "Jordan"
   398 "Kazakhstan"
   404 "Kenya"
   296 "Kiribati"
   408 "Korea (North)"
   410 "Korea (South)"
   414 "Kuwait"
   417 "Kyrgyzstan"
   418 "Lao PDR"
   428 "Latvia"
   422 "Lebanon"
   426 "Lesotho"
   430 "Liberia"
   434 "Libya"
   438 "Liechtenstein"
   440 "Lithuania"
   442 "Luxembourg"
   807 "Macedonia, Republic of"
   450 "Madagascar"
   458 "Malaysia"
   462 "Maldives"
   466 "Mali"
   470 "Malta"
   584 "Marshall Islands"
   474 "Martinique"
   478 "Mauritania"
   480 "Mauritius"
   175 "Mayotte"
   484 "Mexico"
   583 "Micronesia, Federated States of"
   498 "Moldova"
   492 "Monaco"
   496 "Mongolia"
   499 "Montenegro"
   500 "Montserrat"
   504 "Morocco"
   104 "Myanmar"
   516 "Namibia"
   520 "Nauru"
   524 "Nepal"
   528 "Netherlands"
   530 "Netherlands Antilles"
   540 "New Caledonia"
   554 "New Zealand"
   558 "Nicaragua"
   562 "Niger"
   566 "Nigeria"
   570 "Niue"
   574 "Norfolk Island"
   580 "Northern Mariana Islands"
   578 "Norway"
   512 "Oman"
   586 "Pakistan"
   585 "Palau"
   275 "Palestinian Territory"
   591 "Panama"
   598 "Papua New Guinea"
   600 "Paraguay"
   604 "Peru"
   608 "Philippines"
   612 "Pitcairn"
   616 "Poland"
   620 "Portugal"
   630 "Puerto Rico"
   634 "Qatar"
   638 "Réunion"
   642 "Romania"
   643 "Russian Federation"
   652 "Saint-Barthélemy"
   654 "Saint Helena"
   659 "Saint Kitts and Nevis"
   662 "Saint Lucia"
   663 "Saint-Martin (French part)"
   666 "Saint Pierre and Miquelon"
   670 "Saint Vincent and Grenadines"
   882 "Samoa"
   674 "San Marino"
   678 "Sao Tome and Principe"
   682 "Saudi Arabia"
   686 "Senegal"
   688 "Serbia"
   690 "Seychelles"
   694 "Sierra Leone"
   702 "Singapore"
   703 "Slovakia"
   705 "Slovenia"
    90 "Solomon Islands"
   239 "South Georgia and the South Sandwich Islands"
   728 "South Sudan"
   724 "Spain"
   144 "Sri Lanka"
   736 "Sudan"
   740 "Suriname"
   744 "Svalbard and Jan Mayen Islands"
   748 "Swaziland"
   752 "Sweden"
   756 "Switzerland"
   760 "Syrian Arab Republic (Syria)"
   158 "Taiwan, Republic of China"
   762 "Tajikistan"
   834 "Tanzania, United Republic of"
   764 "Thailand"
   626 "Timor-Leste"
   768 "Togo"
   772 "Tokelau"
   776 "Tonga"
   780 "Trinidad and Tobago"
   788 "Tunisia"
   792 "Turkey"
   795 "Turkmenistan"
   796 "Turks and Caicos Islands"
   798 "Tuvalu"
   800 "Uganda"
   804 "Ukraine"
   784 "United Arab Emirates"
   826 "United Kingdom"
   840 "United States of America"
   581 "US Minor Outlying Islands"
   858 "Uruguay"
   860 "Uzbekistan"
   548 "Vanuatu"
   862 "Venezuela (Bolivarian Republic)"
   704 "Viet Nam"
   850 "Virgin Islands, US"
   876 "Wallis and Futuna Islands"
   732 "Western Sahara"
   887 "Yemen"
;
label define DEM_21A 
     1 "Yes"
     2 "No"
;
label define DEM_21  
     1 "No - no difficulty"
     2 "Yes - some difficulty"
     3 "Yes - a lot of difficulty"
     4 "Cannot hear at all"
;
label define DEM_22A 
     1 "Yes"
     2 "No"
;
label define DEM_22  
     1 "No - no difficulty"
     2 "Yes - some difficulty"
     3 "Yes - a lot of difficulty"
     4 "Cannot hear at all"
;
label define DEM_23  
     1 "No - no difficulty"
     2 "Yes - some difficulty"
     3 "Yes - a lot of difficulty"
     4 "Cannot walk at all"
;
label define DEM_24  
     1 "No - no difficulty"
     2 "Yes - some difficulty"
     3 "Yes - a lot of difficulty"
     4 "Cannot speak at all"
;
label define DEM_25  
     1 "No - no difficulty"
     2 "Yes - some difficulty"
     3 "Yes - a lot of difficulty"
     4 "Cannot do at all"
;
label define DEM_26  
     1 "No - no difficulty"
     2 "Yes - some difficulty"
     3 "Yes - a lot of difficulty"
     4 "Cannot do at all"
;
label define DEM_27  
     1 "Yes"
     2 "No"
;
label define P_MORE_ROWS
     1 "Yes, there are additional persons"
     2 "No, list of persons is complete"
;

#delimit cr
label values gharea   GHAREA  
label values ghhrpl   GHHRPL  
label values dem_str  DEM_STR 
label values hc01     HC01    
label values hc02     HC02    
label values hc03     HC03    
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc16     HC16    
label values hc17     HC17    
label values hc18     HC18    
label values hc19     HC19    
label values hc20     HC20    
label values hc21     HC21    
label values hc22     HC22    
label values hc23     HC23    
label values hc24     HC24    
label values hc25     HC25    
label values hc26     HC26    
label values hc27     HC27    
label values hc28     HC28    
label values hc29     HC29    
label values hc30     HC30    
label values hc31     HC31    
label values hc32     HC32    
label values hc33     HC33    
label values hc34     HC34    
label values hc35     HC35    
label values hc36     HC36    
label values hc37     HC37    
label values hc38     HC38    
label values hc39     HC39    
label values hc40     HC40    
label values hc42     HC42    
label values hc43     HC43    
label values hc44     HC44    
label values hc45     HC45    
label values hc46     HC46    
label values hc47     HC47    
label values hc48     HC48    
label values hc49     HC49    
label values hc50     HC50    
label values hc51     HC51    
label values lh5      LH5     
label values lh6      LH6     
label values lh7      LH7     
label values lh8      LH8     
label values lh9      LH9     
label values lh10     LH10    
label values lh11     LH11    
label values ws1      WS1     
label values ws2      WS2     
label values ws3      WS3     
label values ws4      WS4     
label values ws5      WS5     
label values hh_introduction HH_INTRODUCTION
label values hh_conclusion HH_CONCLUSION
label values hh_gps_reading HH_GPS_READING
label values p00_population_introduction P00_POPULATION_INTRODUCTION
label values d00_dwelling_introduction D00_DWELLING_INTRODUCTION
label values lh_livelihood_introduction LH_LIVELIHOOD_INTRODUCTION
label values e00_emigration_introduction E00_EMIGRATION_INTRODUCTION
label values e01_emigration E01_EMIGRATION
label values e07      E07     
label values e08      E08     
label values e09      E09     
label values e10      E10     
label values p_keep_row P_KEEP_ROW
label values dem_01   DEM_01  
label values dem_02   DEM_02  
label values dem_03   DEM_03  
label values dem_04   DEM_04  
label values dem_07   DEM_07  
label values dem_08   DEM_08  
label values dem_09   DEM_09  
label values dem_10   DEM_10  
label values dem_11   DEM_11  
label values dem_12   DEM_12  
label values dem_13a  DEM_13A 
label values dem_14   DEM_14  
label values dem_15   DEM_15  
label values dem_17   DEM_17  
label values dem_18   DEM_18  
label values dem_20   DEM_20  
label values dem_21a  DEM_21A 
label values dem_21   DEM_21  
label values dem_22a  DEM_22A 
label values dem_22   DEM_22  
label values dem_23   DEM_23  
label values dem_24   DEM_24  
label values dem_25   DEM_25  
label values dem_26   DEM_26  
label values dem_27   DEM_27  
label values p_more_rows P_MORE_ROWS
